apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ddos-api-netpol
  namespace: ddos-detection
spec:
  podSelector:
    matchLabels:
      app: ddos-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ddos-detection
      ports:
        - port: 8000
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - port: 8000
          protocol: TCP
  egress:
    - {}
